
package Frames;

import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 * Clase donde se mostrarán los hoteles registrados.
 * @author Canché Sastré Marlon Alejandro
 * @author Sánchez Rentería Juan Diego
 */
public class frmHoteles extends javax.swing.JFrame {

    MongoClient mongoClient = new MongoClient("localhost", 27017);
    MongoDatabase database = mongoClient.getDatabase("hotel_proyecto");
    MongoCollection<Document> hotelCollection = database.getCollection("hotel");
    MongoCollection<Document> categoriaCollection = database.getCollection("categoria");
    ArrayList<String> hoteles;
    String hotelSeleccionado;


    /**
     * Método constructor de la clase.
     */
    public frmHoteles() {
        this.hoteles = new ArrayList<>();
        this.hotelSeleccionado = "";
        initComponents();
//        insertar();
        mostrar();
    }

    /**
     * Método para insertar datos referentes a los hoteles.
     */
    private void insertar() {
//        Document hotel= new Document("_id","2")
//                .append("nombre", "El Dorado")
//                .append("direccion", "Avenida El Pino 522")
//                .append("telefono", 6442654321L)
//                .append("anioConstruccion", "2017")
//                .append("idCategoria", "2");
//        
//        hotelCollection.insertOne(hotel);
//        
//        Document categoria = new Document("_id","2")
//                .append("estrellas", 4.0)
//                .append("IVA", 4.5);
//        
//        categoriaCollection.insertOne(categoria);
    }

    /**
     * Método para mostrar los datos de las habitaciones registradas.
     */    
    private void mostrar() {
        MongoCursor<Document> cursor = hotelCollection.find().iterator();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombre");
        model.addColumn("Dirección");
        model.addColumn("Teléfono");
        model.addColumn("Año Construcción");
        model.addColumn("Estrellas");
        model.addColumn("IVA");

        while (cursor.hasNext()) {
            Document doc = cursor.next();
            Document user = categoriaCollection.find(eq("_id", doc.getString("idCategoria"))).first();
            model.addRow(new Object[]{
                doc.getString("nombre"),
                doc.getString("direccion"),
                doc.getLong("telefono"),
                doc.getString("anioConstruccion"),
                user.getDouble("estrellas"),
                user.getDouble("IVA")
            });

            tblHoteles.setModel(model);

            this.hoteles.add(doc.getString("_id"));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoteles = new javax.swing.JTable();
        btnVerHabitaciones = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Todos los hoteles disponibles de Hotel Inn");

        tblHoteles.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        tblHoteles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHoteles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHotelesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoteles);

        btnVerHabitaciones.setBackground(new java.awt.Color(255, 255, 204));
        btnVerHabitaciones.setText("Ver habitaciones");
        btnVerHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHabitacionesActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(255, 255, 204));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(254, 254, 254))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVerHabitaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerHabitaciones)
                    .addComponent(btnVolver))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para la selección de un hotel en la tabla.
     * @param evt Evento que accionó el método.
     */
    private void tblHotelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHotelesMouseClicked
        // TODO add your handling code here:
        int row = this.tblHoteles.getSelectedRow();
        this.hotelSeleccionado = this.hoteles.get(row);
        System.out.println("HOTEL: " + hotelSeleccionado);
    }//GEN-LAST:event_tblHotelesMouseClicked

    /**
     * Botón para redireccionar a las habitaciones asociadas al hotel.
     * @param evt Evento que accionó el botón.
     */
    private void btnVerHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHabitacionesActionPerformed
        // TODO add your handling code here:
        if (!"".equals(this.hotelSeleccionado)) {
            frmHabitaciones newFrm = new frmHabitaciones();
            newFrm.setHotelSeleccionado(hotelSeleccionado);
            newFrm.mostrar();
            newFrm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnVerHabitacionesActionPerformed

    /**
     * Botón para volver al menú principal de la habitación.
     * @param evt Evento que accionó el botón.
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        frmInicio newFrm = new frmInicio();
        newFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerHabitaciones;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoteles;
    // End of variables declaration//GEN-END:variables
}
